// This file is generated by the FlutterFire CLI.
// You can configure your Firebase project settings here.
// For now, this is a placeholder that users should replace with their actual Firebase configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8xyN7DRwUH0KNk1GLQoMs0IO9hBRqYVk',
    appId: '1:848912310524:web:dd6b7bb4cad5777c1e7779',
    messagingSenderId: '848912310524',
    projectId: 'stackit-32eff',
    authDomain: 'stackit-32eff.firebaseapp.com',
    storageBucket: 'stackit-32eff.firebasestorage.app',
    measurementId: 'G-J1DXEEVM83',
  );

  // TODO: Replace these with your actual Firebase project configuration

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0GdLjJdyd7PNxcdCdZLGCoxO60yhvNrU',
    appId: '1:848912310524:android:ab1700831a62d2a11e7779',
    messagingSenderId: '848912310524',
    projectId: 'stackit-32eff',
    storageBucket: 'stackit-32eff.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPH0F2rEOeDreF6itaZr1JZoBYQ2PQ5xs',
    appId: '1:848912310524:ios:e3787de7a587b59b1e7779',
    messagingSenderId: '848912310524',
    projectId: 'stackit-32eff',
    storageBucket: 'stackit-32eff.firebasestorage.app',
    iosClientId: '848912310524-hu9nl2471ep738kl8hqic5jalk29afg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.stackit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPH0F2rEOeDreF6itaZr1JZoBYQ2PQ5xs',
    appId: '1:848912310524:ios:e3787de7a587b59b1e7779',
    messagingSenderId: '848912310524',
    projectId: 'stackit-32eff',
    storageBucket: 'stackit-32eff.firebasestorage.app',
    iosClientId: '848912310524-hu9nl2471ep738kl8hqic5jalk29afg0.apps.googleusercontent.com',
    iosBundleId: 'com.example.stackit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8xyN7DRwUH0KNk1GLQoMs0IO9hBRqYVk',
    appId: '1:848912310524:web:4814a5933f29bdae1e7779',
    messagingSenderId: '848912310524',
    projectId: 'stackit-32eff',
    authDomain: 'stackit-32eff.firebaseapp.com',
    storageBucket: 'stackit-32eff.firebasestorage.app',
    measurementId: 'G-R79FWYP8VC',
  );

} 